//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaKiralama.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralamalar
    {
        public int KiralamalarID { get; set; }
        public int VillaID { get; set; }
        public int MusteriD { get; set; }
        public System.DateTime BaslamaTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Villalar Villalar { get; set; }
    }
}
