//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaKiralama.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.Kiralamalar = new HashSet<Kiralamalar>();
        }
    
        public int MusterilerID { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
        public string MusteriAdres { get; set; }
        public string MusteriTelefon { get; set; }
        public string MusteriTC { get; set; }
        public string Email { get; set; }
        public string MusteriCinsiyet { get; set; }
        public Nullable<System.DateTime> MusteriDogumTarihi { get; set; }
        public Nullable<int> IlceID { get; set; }
    
        public virtual ilceler ilceler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kiralamalar> Kiralamalar { get; set; }
    }
}
