//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaKiralama.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VillaResimler
    {
        public int VillaResimlerID { get; set; }
        public int VillaID { get; set; }
        public string ResimYolu { get; set; }
        public Nullable<System.DateTime> ResimEklemeTarihi { get; set; }
        public string ResimAdi { get; set; }
    
        public virtual Villalar Villalar { get; set; }
    }
}
