//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillaKiralama.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Villalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Villalar()
        {
            this.Kiralamalar = new HashSet<Kiralamalar>();
            this.VillaDetay = new HashSet<VillaDetay>();
            this.VillaResimler = new HashSet<VillaResimler>();
        }
    
        public int VillalarID { get; set; }
        public int KategoriID { get; set; }
        public string VillaAdi { get; set; }
        public string VillaAdres { get; set; }
        public int VillaImageID { get; set; }
        public int VillaIlceID { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual ilceler ilceler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kiralamalar> Kiralamalar { get; set; }
        public virtual VillaKategorileri VillaKategorileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VillaDetay> VillaDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VillaResimler> VillaResimler { get; set; }
    }
}
